In [1]:
import numpy as np
from numpy import linalg as LA

In [2]:
def SVD(A):
    e_val, e_vec = LA.eig(A.T@A)
    V = e_vec
    print(f"{V.T = }")
    S = np.sqrt(e_val)
    print(f"{S = }")
    U = A@(e_vec/S)
    return U, S, V.T

In [3]:
# A = np.array(
#     [
#         [1, 1],
#         [0, -1.01],
#         [-1, 1]
#     ]
# )

A = np.array(
    [
        [3, 2, 2],
        [2, 3, -2]
    ]
)

U, S, V = SVD(A)
S = np.diag(S)

V.T = array([[-7.07106781e-01, -7.07106781e-01, -4.55680392e-17],
       [-6.66666667e-01,  6.66666667e-01,  3.33333333e-01],
       [ 2.35702260e-01, -2.35702260e-01,  9.42809042e-01]])
S = array([5.0000000e+00, 7.0939642e-08, 3.0000000e+00])


In [4]:
print(f"U = \n{U}\n")
print(f"S = \n{S}\n")
print(f"V = \n{V}\n")

U = 
[[-7.07106781e-01  0.00000000e+00  7.07106781e-01]
 [-7.07106781e-01 -1.11758709e-08 -7.07106781e-01]]

S = 
[[5.0000000e+00 0.0000000e+00 0.0000000e+00]
 [0.0000000e+00 7.0939642e-08 0.0000000e+00]
 [0.0000000e+00 0.0000000e+00 3.0000000e+00]]

V = 
[[-7.07106781e-01 -7.07106781e-01 -4.55680392e-17]
 [-6.66666667e-01  6.66666667e-01  3.33333333e-01]
 [ 2.35702260e-01 -2.35702260e-01  9.42809042e-01]]



In [5]:
# checking if actually A = U*S*V
A == U @ S @ V

array([[False,  True,  True],
       [False, False, False]])